from src.models.spar_models import SparProducts
from src.models.relex_models import RelexProducts
from src.mappers.base_mapper import BaseMapper
from src.utils.export_config import ExportConfig

class ProductsMapper(BaseMapper[SparProducts, RelexProducts]):
    def map(self, source: SparProducts) -> RelexProducts:
        return RelexProducts(
            product=ExportConfig.clean_string(source.product),
            name=ExportConfig.clean_string(source.name),
            group=ExportConfig.clean_code(source.group),
            weight=source.weight,
            weight_unit=ExportConfig.clean_string(source.weight_unit),
            ean=ExportConfig.clean_string(source.ean),
            # alternative_code=ExportConfig.clean_string(source.alternative_code),
            # order_quantity=source.order_quantity,
            introduction_date=source.introduction_date,
            termination_date=source.termination_date,
            # required_remaining_shelf_life=source.required_remaining_shelf_life,
            # reference_spoiling_time=source.reference_spoiling_time,
            inventory_unit=ExportConfig.clean_string(source.inventory_unit),
            height=source.height,
            depth=source.depth,
            width=source.width,
            dimension_unit=ExportConfig.clean_string(source.dimension_unit),
            volume_unit=ExportConfig.clean_string(source.volume_unit),
            volume=source.volume,
            box_size=source.box_size,
            pallet_size=source.pallet_size,
            # image_url=ExportConfig.clean_string(source.image_url),
            # variant_type=ExportConfig.clean_string(source.variant_type),
            # brand_code=ExportConfig.clean_string(source.brand_code),
            # brand=ExportConfig.clean_string(source.brand),
            # is_private_label=source.is_private_label,
            # brand_tier=ExportConfig.clean_string(source.brand_tier),
            # price_family=ExportConfig.clean_string(source.price_family),
            # line_group=ExportConfig.clean_string(source.line_group),
            # is_kvi=source.is_kvi,
            # kvi_group=ExportConfig.clean_string(source.kvi_group),
            supplier=ExportConfig.clean_string(source.supplier),
            # manufacturer=ExportConfig.clean_string(source.manufacturer),
            # merchandising_style=ExportConfig.clean_string(source.merchandising_style),
            # case_height=source.case_height,
            # case_depth=source.case_depth,
            # case_width=source.case_width,
            # case_units_high=source.case_units_high,
            # case_units_deep=source.case_units_deep,
            # case_units_wide=source.case_units_wide,
            # case_pack_units=source.case_pack_units,
            # nesting_height=source.nesting_height,
            # nesting_depth=source.nesting_depth,
            # nesting_width=source.nesting_width,
            # squeeze_height=source.squeeze_height,
            # squeeze_depth=source.squeeze_depth,
            # squeeze_width=source.squeeze_width,
            # tray_height=source.tray_height,
            # tray_depth=source.tray_depth,
            # tray_width=source.tray_width,
            # tray_units_high=source.tray_units_high,
            # tray_units_deep=source.tray_units_deep,
            # tray_units_wide=source.tray_units_wide,
            # tray_pack_units=source.tray_pack_units,
            # shape=ExportConfig.clean_string(source.shape),
            # peg_x=ExportConfig.clean_string(source.peg_x),
            # peg_y=ExportConfig.clean_string(source.peg_y),
            # number_of_peg_holes=source.number_of_peg_holes,
            # peg_depth=source.peg_depth,
            # max_stack=source.max_stack,
            # max_top_cap=source.max_top_cap,
            # max_right_cap=source.max_right_cap,
            # max_deep_cap=source.max_deep_cap,
            # min_deep=source.min_deep,
            # max_deep=source.max_deep,
            # front_overhang=source.front_overhang,
            # finger_space_above=source.finger_space_above,
            # finger_space_to_the_side=source.finger_space_to_the_side,
            # orientation_type=ExportConfig.clean_string(source.orientation_type),
            # can_break_tray_up=source.can_break_tray_up,
            # can_break_tray_down=source.can_break_tray_down,
            # can_break_tray_top=source.can_break_tray_top,
            # can_brak_tray_back=source.can_brak_tray_back,
            # merchandising_net_content=source.merchandising_net_content,
            # merchandising_unit_of_measure=ExportConfig.clean_string(source.merchandising_unit_of_measure),
            # sell_pack_count=source.sell_pack_count,
            # sell_pack_description=ExportConfig.clean_string(source.sell_pack_description),
            # sell_pack_product=ExportConfig.clean_string(source.sell_pack_product),
            # reference_code=ExportConfig.clean_string(source.reference_code)
        )
